import requests

urls = ['https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/ayu.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Brogrammer.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Bright%20Lights.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Ciapre.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Dracula.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/FirefoxDev.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Firewatch.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Flatland.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/FrontEndDelight.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Galaxy.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Highway.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Hybrid.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Lab%20Fox.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/LiquidCarbon.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Neutron.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/OceanicMaterial.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Relaxed.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Tomorrow%20Night.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Treehouse.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Wombat.itermcolors', 'https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Wryan.itermcolors']
names = [url[80:].replace('%20', '-').lower() for url in urls]

for i, j in zip(urls, names):
    with open(f'/Users/js/.iterm/{j}', 'w') as f:
        r = requests.get(i)
        f.write(r.text)
